# build stage
FROM node:24-alpine AS build-stage

ARG PUBLIC_URL=/

RUN corepack enable yarn && apk add --no-cache autoconf automake libtool make tiff jpeg zlib zlib-dev pkgconf nasm file gcc g++ musl-dev python3 git

WORKDIR /app
COPY ./.yarn /app/.yarn
COPY package.json yarn.lock .yarnrc.yml /app/
RUN yarn install --immutable

COPY vite.config.mjs index.html README.md /app/

COPY ./bin /app/bin
COPY ./build/loaders /app/build/loaders
COPY ./build/vite-plugin-generated-assets.mjs /app/build/vite-plugin-generated-assets.mjs
COPY ./public /app/public
COPY ./translations /app/translations
COPY ./src /app/src

RUN yarn run validateTranslations && VUE_APP_PUBLIC_URL=${PUBLIC_URL} yarn run build:dev

FROM nginx:stable-alpine
RUN mkdir /app
COPY --from=build-stage /app/dist/dev /app
COPY nginx.conf /etc/nginx/nginx.conf
