# build stage
FROM node:16-alpine as build-stage

ARG PUBLIC_URL=/

RUN apk add --no-cache autoconf automake libtool make tiff jpeg zlib zlib-dev pkgconf nasm file gcc g++ musl-dev python3 git

WORKDIR /app
COPY package.json yarn.lock /app/
RUN yarn install

COPY babel.config.js vue.config.js README.md /app/

COPY ./bin /app/bin
COPY ./build/loaders /app/build/loaders
COPY ./public /app/public
COPY ./translations /app/translations
COPY ./src /app/src

RUN yarn run validateTranslations && VUE_APP_PUBLIC_URL=${PUBLIC_URL} yarn run build:dev

FROM nginx:stable-alpine
RUN mkdir /app
COPY --from=build-stage /app/dist/dev /app
COPY nginx.conf /etc/nginx/nginx.conf
