name: Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Install build dependencies
        run: sudo apt-get install autoconf libtool pkg-config nasm build-essential libpng-dev
      - name: Install dependencies
        run: yarn install
      - name: Validate translations
        run: yarn validateTranslations
      - name: Build for production
        run: yarn build
        env:
          VUE_APP_PUBLIC_URL: https://roshar.17thshard.com/
          VUE_APP_GA_ID: ${{ secrets.GA_ID }}
      - name: Create CNAME
        uses: finnp/create-file-action@master
        env:
          FILE_NAME: "./dist/release/CNAME"
          FILE_DATA: "roshar.17thshard.com"

      - name: Deploy
        uses: maxheld83/ghpages@v0.2.1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && contains(github.event.head_commit.message, '[deploy]')
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          BUILD_DIR: dist/release/
