name: Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Install dependencies
        uses: Borales/actions-yarn@v2.1.0
        with:
          cmd: install
      - name: Compile Lang JSONs
        uses: Borales/actions-yarn@v2.1.0
        with:
          cmd: compileLangJsons
      - name: Copy Lang JSONs
        run: |
          cp build/lang/* src/lang
      - name: Build for production
        uses: Borales/actions-yarn@v2.1.0
        env:
          VUE_APP_PUBLIC_URL: https://roshar.17thshard.com/
          VUE_APP_GA_ID: ${{ secrets.GA_ID }}
        with:
          cmd: build
      - name: Create CNAME
        uses: finnp/create-file-action@master
        env:
          FILE_NAME: "./dist/release/CNAME"
          FILE_DATA: "roshar.17thshard.com"

      - name: Deploy
        uses: maxheld83/ghpages@v0.2.1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && contains(github.event.head_commit.message, '[deploy]')
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          BUILD_DIR: dist/release/
